apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaopeso
spec:
  replicas: 2
  selector:
    matchLabels:
      app: peso
  template:
    metadata:
      name: conversaopeso
      labels:
        app: peso
    spec:
      containers:
        - name: peso
          image: marcelobh89/conversao-peso:latest
          ports:
          - containerPort: 80
